### ISSUE TITLE
Todo list untuk v2

### ISSUE THREAD

**Issue by fakhrullah** [fakhrullah/nasihati#28]
Target untuk v2

1. Menggunakan MVC. Guna controller, model dan mongoose.
2. Artikel guide step by step untuk other developer. Contribution guide; step by step to start program, step by step to contribute (linting for js, pug and css).
3. Setiap nasihat ada link masing2 supaya boleh di share di sosial media. Sebenarnya dah ada, cthnya: /nasihat/:id - tapi masih tak digunakan di homepage. Idea baru ialah, homepage akan redirect ke page ini daripada guna AJAX.
4. Form page untuk edit nasihat. Dah ada juga tapi, tak confirm lagi menjadi ke tak, sebab dah lama tinggal. Syarat edit nasihat, sesiapa pun boleh edit, dan setiap edit akan di revisionkan sehingga admin approve.

### TODO
- [x] Ganti config.js dengan .env
- [x] Buang console.log, ganti dengan winstonjs logger
- [ ] CRUD page dan controller untuk nasihat
  - [ ] Form untuk tambah nasihat. Hanya admin yg boleh akses ini. `GET /nasihat/create`
  - [ ] Tambah nasihat. Hanya admin yg boleh akses ini. `POST /nasihat/`
  - [ ] Tunjuk nasihat. Sekarang, main page, tapi nanti akan buat main page, redirect ke page tunjuk nasihat. `GET /nasihat/:id`
  - [ ] Form untuk edit nasihat teks. Sebab mungkin admin tersilap taip, atau tulis ayat tak tepat. Untuk form sy akan guna revisions untuk setiap nasihat. Jadi sy akan buka untuk sesiapa saja edit, tapi hanya admin yg boleh approve yg mana boleh diterima. `GET /nasihat/edit/:id`
  - [ ] Handle edit nasihat update. `PUT /nasihat/:id`
  - [ ] Page list senarai nasihat (dgn pagination) untuk delete dan approve revision. Hanya admin yg boleh akses. `GET /nasihat/`
  - [ ] Handle approve nasihat. Hanya admin. `POST /nasihat/:id/:revisionId/approve`
  - [ ] Handle delete nasihat. Hanya admin. `DELETE /nasihat/:id`
  - [ ] Handle delete nasihat revision. Hanya admin. `DELETE /nasihat/:id/:revisionId`
- [ ] Rethinking model schema untuk nasihat. Ingat mesti ada revision.
- [ ] Admin middleware.
- [ ] UI baru.
  - [ ] Ada button untuk edit nasihat.
  - [ ] Main page hanya redirect ke /nasihat/:id
  - [ ] Ada button untuk share nasihat. Bila klik button tu, tunjuk uneditable input, yg ada link ke page semasa iaitu `domain/nasihat/:id'
  - [ ] Background yg sama dan color yg sama agak boring, jadi, cuba cari inspiration biar, warna dan background berbeza. Tapi bukan random, sebab kalau pakai random, nanti orang share dgn niat background n color lain, tp tiba2 org yg buka link x dapat tengok benda yg sama.
 
Ada idea lain?
